/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    alumni: AlumnusAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    alumni: Alumnus;
    media: Media;
    jobs: Job;
    groups: Group;
    'social-links': SocialLink;
    articles: Article;
    posts: Post;
    offres: Offre;
    evenements: Evenement;
    discussions: Discussion;
    'direct-messages': DirectMessage;
    'public-messages': PublicMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    alumni: AlumniSelect<false> | AlumniSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    offres: OffresSelect<false> | OffresSelect<true>;
    evenements: EvenementsSelect<false> | EvenementsSelect<true>;
    discussions: DiscussionsSelect<false> | DiscussionsSelect<true>;
    'direct-messages': DirectMessagesSelect<false> | DirectMessagesSelect<true>;
    'public-messages': PublicMessagesSelect<false> | PublicMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Alumnus;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AlumnusAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni".
 */
export interface Alumnus {
  id: number;
  prenom: string;
  nom: string;
  statut?: ('etudiant' | 'alumni') | null;
  bio?: string | null;
  telephone?: string | null;
  ville?: string | null;
  diplome?: string | null;
  promotion?: number | null;
  poste?: string | null;
  entreprise?: string | null;
  experiences?:
    | {
        poste: string;
        entreprise: string;
        localite: string;
        isCurrent?: boolean | null;
        dateDebut: string;
        dateFin?: string | null;
        description?: string | null;
        matchFormation?: boolean | null;
        secteur?: string | null;
        typeContrat?: string | null;
        isCadre?: boolean | null;
        remuneration?: string | null;
        provenanceEmploi?: string | null;
        id?: string | null;
      }[]
    | null;
  formations?:
    | {
        nom: string;
        etablissement: string;
        annee?: string | null;
        isENC?: boolean | null;
        id?: string | null;
      }[]
    | null;
  interets?:
    | {
        nom: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stocke les icônes, labels et URLs/IDs de fichiers.
   */
  socialLinks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  photo?: (number | null) | Media;
  isMentor?: boolean | null;
  linkedin?: string | null;
  instagram?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'alumni';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  titre: string;
  entreprise: string;
  ville: string;
  typeContrat: 'cdi' | 'cdd' | 'alternance' | 'stage';
  secteur?: string | null;
  remuneration?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  dateLimite?: string | null;
  posterPar: number | Alumnus;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  titre: string;
  slug: string;
  categorie: 'bts_sio' | 'entrepreneuriat' | 'vie_etudiante' | 'entraide';
  description: string;
  miniature: number | Media;
  banniere: number | Media;
  isPublic?: boolean | null;
  restrictDiplome?: string | null;
  restrictCampus?: string | null;
  restrictCategorie?: string | null;
  restrictPromotion?: string | null;
  membres?: (number | Alumnus)[] | null;
  /**
   * Le créateur du groupe (Attribué automatiquement)
   */
  createur?: (number | null) | Alumnus;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  icon: string;
  label: string;
  url?: string | null;
  file?: (number | null) | Media;
  owner: number | Alumnus;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  titre: string;
  slug: string;
  description: string;
  contenu: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categorie: 'vie_etablissement' | 'portraits_anciens' | 'international' | 'evenements';
  statut?: ('publie' | 'brouillon' | 'attente') | null;
  couverture: number | Media;
  auteur?: (number | null) | Alumnus;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  contenu: string;
  image?: (number | null) | Media;
  auteur: number | Alumnus;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offres".
 */
export interface Offre {
  id: number;
  poste: string;
  entreprise: string;
  typeContrat: 'CDI' | 'CDD' | 'Alternance' | 'Stage' | 'Independant';
  localisation?: string | null;
  description?: string | null;
  statut?: ('publie' | 'brouillon') | null;
  secteur?: string | null;
  remuneration?: string | null;
  experience?: string | null;
  dateDebut?: string | null;
  dateLimite?: string | null;
  logo?: (number | null) | Media;
  documentJoint?: (number | null) | Media;
  restreindreDiplomes?: ('bts' | 'dcg3' | 'prepa')[] | null;
  restreindreCampus?: ('enc_bessieres' | 'enc_bessieres_apprentissage')[] | null;
  restreindrePromotions?: ('2026' | '2027' | '2028' | '2029' | '2030' | '2031')[] | null;
  recruteur?: (number | null) | Alumnus;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements".
 */
export interface Evenement {
  id: number;
  nom: string;
  slug: string;
  typeLocalisation: 'presentiel' | 'enligne';
  dateDebut: string;
  dateFin: string;
  categorie: 'conference' | 'reseau' | 'atelier' | 'jpo';
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  modeInscription: 'plateforme' | 'externe' | 'libre';
  lienExterne?: string | null;
  statut?: ('publie' | 'brouillon' | 'attente') | null;
  couverture: number | Media;
  organisateur?: (number | null) | Alumnus;
  participants?: (number | Alumnus)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussions".
 */
export interface Discussion {
  id: number;
  titre: string;
  contenu: string;
  auteur: number | Alumnus;
  commentaires?:
    | {
        auteur: number | Alumnus;
        message: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "direct-messages".
 */
export interface DirectMessage {
  id: number;
  from: number | Alumnus;
  to: number | Alumnus;
  message?: string | null;
  file?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-messages".
 */
export interface PublicMessage {
  id: number;
  user: string;
  text: string;
  time: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'alumni';
        value: number | Alumnus;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'social-links';
        value: number | SocialLink;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'offres';
        value: number | Offre;
      } | null)
    | ({
        relationTo: 'evenements';
        value: number | Evenement;
      } | null)
    | ({
        relationTo: 'discussions';
        value: number | Discussion;
      } | null)
    | ({
        relationTo: 'direct-messages';
        value: number | DirectMessage;
      } | null)
    | ({
        relationTo: 'public-messages';
        value: number | PublicMessage;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'alumni';
        value: number | Alumnus;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'alumni';
        value: number | Alumnus;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni_select".
 */
export interface AlumniSelect<T extends boolean = true> {
  prenom?: T;
  nom?: T;
  statut?: T;
  bio?: T;
  telephone?: T;
  ville?: T;
  diplome?: T;
  promotion?: T;
  poste?: T;
  entreprise?: T;
  experiences?:
    | T
    | {
        poste?: T;
        entreprise?: T;
        localite?: T;
        isCurrent?: T;
        dateDebut?: T;
        dateFin?: T;
        description?: T;
        matchFormation?: T;
        secteur?: T;
        typeContrat?: T;
        isCadre?: T;
        remuneration?: T;
        provenanceEmploi?: T;
        id?: T;
      };
  formations?:
    | T
    | {
        nom?: T;
        etablissement?: T;
        annee?: T;
        isENC?: T;
        id?: T;
      };
  interets?:
    | T
    | {
        nom?: T;
        id?: T;
      };
  socialLinks?: T;
  photo?: T;
  isMentor?: T;
  linkedin?: T;
  instagram?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  titre?: T;
  entreprise?: T;
  ville?: T;
  typeContrat?: T;
  secteur?: T;
  remuneration?: T;
  description?: T;
  dateLimite?: T;
  posterPar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  categorie?: T;
  description?: T;
  miniature?: T;
  banniere?: T;
  isPublic?: T;
  restrictDiplome?: T;
  restrictCampus?: T;
  restrictCategorie?: T;
  restrictPromotion?: T;
  membres?: T;
  createur?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  icon?: T;
  label?: T;
  url?: T;
  file?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  description?: T;
  contenu?: T;
  categorie?: T;
  statut?: T;
  couverture?: T;
  auteur?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  contenu?: T;
  image?: T;
  auteur?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offres_select".
 */
export interface OffresSelect<T extends boolean = true> {
  poste?: T;
  entreprise?: T;
  typeContrat?: T;
  localisation?: T;
  description?: T;
  statut?: T;
  secteur?: T;
  remuneration?: T;
  experience?: T;
  dateDebut?: T;
  dateLimite?: T;
  logo?: T;
  documentJoint?: T;
  restreindreDiplomes?: T;
  restreindreCampus?: T;
  restreindrePromotions?: T;
  recruteur?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements_select".
 */
export interface EvenementsSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  typeLocalisation?: T;
  dateDebut?: T;
  dateFin?: T;
  categorie?: T;
  description?: T;
  modeInscription?: T;
  lienExterne?: T;
  statut?: T;
  couverture?: T;
  organisateur?: T;
  participants?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussions_select".
 */
export interface DiscussionsSelect<T extends boolean = true> {
  titre?: T;
  contenu?: T;
  auteur?: T;
  commentaires?:
    | T
    | {
        auteur?: T;
        message?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "direct-messages_select".
 */
export interface DirectMessagesSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  message?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-messages_select".
 */
export interface PublicMessagesSelect<T extends boolean = true> {
  user?: T;
  text?: T;
  time?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}